### ISSUE TITLE
New USB 3.0 camera

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/eeDAP#10]
Get new USB 3.0 camera work.

**Comment by brandon-gallas** [comment]
How is performance? Show me sometime.

**Comment by qigongFDA** [comment]
In the camera box there is no cable. I found 3 kinds of cables from their website

![image](https://cloud.githubusercontent.com/assets/12702285/10911781/71fe8b22-8214-11e5-9f70-8c1367cd8673.png)

I contacted point grey to figure out which one is suitable for us, and they replied as following:

"Hello Qi,
Yes you are right.
You need to buy the cables separately.
It is not included in the camera.
You should also able to use any decent USB3 cables.
The difference between 3 cables are the length of the cable, and temperature
rating.
Unless you are running your system in high temperature environment, I don't
believe it is necessary to use high temperature rating cables.\
Jieun"

I think we should by the 5 meter normal temperature rating cable.

**Comment by brandon-gallas** [comment]
Editing for English:
Let -> Get
I think we should by -> I think we should buy

We want to purchase the 5 meter cable. Please put this on your to-do poster.

**Comment by qigongFDA** [comment]
I am sorry for the mistake. And thank you very much for your checking. I edited them.

**Comment by qigongFDA** [comment]
The new USB 3.0 camera need pointgrey adapter from image acquisition toolbox. It is a new adapter. We downloaded MATLAB 2016a to get it.

Pointgrey adapter doesn't have 1024x768 model. We need choose a new one for it. 

When we run open the camera. The image start with green, it takes about 10s to get normal color. 

We might need a longer cable with screw

**Comment by qigongFDA** [comment]
Camera is working. Could we close this issue?
