### ISSUE TITLE
whole manual overhaul

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/eeDAP#12]
We need to update, edit and reorganize eeDAP manual.

**Comment by ajhandoko** [comment]
Changes needed to be made with eeDAP manual
	III. Hardware and Software
o	Correct stage name “Ludi”
o	Setting a different stage? (The procedure) 
o	Shorten the requirements
o	Give what is actually needed to get the experiment done
o	Change “Error” to “Possible Error”
	Move directory structure to Workflow
o	Explain the directory structure  Installing (Where the files go)
	V. Output
o	Files & Images
	Topic: Inputs
o	Place the “Free Text” label on the images
o	Examples of Input files
	Label A&B
	Move Utilities to II. Getting Started
	Add short descriptions for “Display” & “Scanners”
	Organize variables
	Pre-Complied Files for testing?
	V. eeDAP Developers
o	Change the topic name to “For eeDAP Developers
	Give Credit (In the Introduction)

**Comment by brandon-gallas** [comment]
Way to stay organized.
BTW, Hardware manufacturer is Ludl. The last letter is L, as in last letter.

Brandon

**Comment by qigongFDA** [comment]
Fahime helped us to test eeDAP and new manual. She still need some help from me to run eeDAP. It took us more than 1 hour to run. Here are some suggestions from her and problem I found 
1.  The line space is a little small
2.  We should use exact word in software (eeDAP3p0.zip, Extract ROI,, GOTO position)
3. How to choose sample input file base on user hardware
4. How to load glass slide, choose lens following input file. 
5. We might need a back button to go back to Running eeDAP page. 
6. In registration, explain "unique location" in a little detail
7. In high resolution registration, we should ask user choose "unique location" in displayed WSI area.
8. We might need screen shot for each task.

**Comment by ajhandoko** [comment]
Qi, 
What do you mean by "a back button" in number 5?
I also need screenshots from each different task.
Also, can you look at the High Resolution Registrations in the Workflow? Should I add screenshots for Step 4?
We also need to figure out how we can shorten the Requirements down.
Lastly, where should I put the credits and how should I format it?

**Comment by qigongFDA** [comment]
Hello Jessica,
1. Back Button: In " Running eeDAP" page. We create a lot of link to work follow pages. And maybe in the work follow pages we should create a button or link back to " Running eeDAP" page. Then reader could switch between them smoothly.
2. OK. I think the next step is update all the GUIs. We also add some new buttons. 
3. We could add HRR image but don't have to. Because, A. We have image for low resolution registration they are very similar; B. The HRR image is much larger then those button images. I am afraid big image affects page uniform. 
4. Yes, I have some ideas (The titles in Running eeDAP page)
5. I think we could add credits in or after Introduction temperately.

**Comment by ajhandoko** [comment]
Credits: Who are all the people involved with eeDAP or who have helped in the past?

**Comment by brandon-gallas** [comment]
Brandon Gallas: 6/2012 - present
- Project lead and software development

Qi Gong: All contributions are recorded on github. Please write a description of your contributions (100 words or less). You can mention that github has recorded your work.

Jessica Handoko: Please write a description of your contributions (100 words or less). You can mention that github has recorded your work if that is appropriate.

Tyler Keay: 7/2012 - 4/2013
- Create user manual, improve eeDAP workflow and registration precision, consolidate distribution and create self-contained software package, modify hardware for simultaneous viewing of specimen (camera and eyepiece), manage first pilot study

Neil O'Flaherty: 7/2102 - 4/2013
- Evaluate registration precision, investigate WSI file formats and resolution (physical relationship between WSI resolution, the camera, and stage steps), organize hardware specifications and manuals

Adam Ivansky: 6/2012 - 8/2012
- Original creator

**Comment by brandon-gallas** [comment]
We should also at least list other people that have helped: Wei-Chung Cheng, Stephen Hewitt, Catherine Conway, Marios Gavrielides, Adam Wunderlich.

**Comment by ajhandoko** [comment]
For the Hardware Requirements:
What pages can I start to delete/remove?

**Comment by brandon-gallas** [comment]
First, nice job using this platform to communicate. I'm impressed by what I have seen, and I'm looking forward to the completion of the overhaul.

BTW, I assume that questions are for @qigongFDA unless you ask for me to answer.

**Comment by qigongFDA** [comment]
Hello Brandon,

Yes. The question is for me. I will work with Jessica when she come here next time, and then post result.  Thank you.

Qi

**Comment by qigongFDA** [comment]
I asked Ashley help us to test our manual, here are some problem we found
P6:  
1.	eeDAP address is not correct
P7: 
1.	“*If this is your first time using eeDAP, we recommend you go to the Workflow page for more informationon how to run eeDAP.” Bring her to workflow and skip Run software.
2.	Download Sample WSI Image
3.	How to start eeDAP (Mention it might take some time to avoid multiple clicks)
4.	Mention Extract ROI button
5.	If not choose MircoRT, continue to eeDAP study. And mention if user want to use MircoRT, he has to have both WSI and glassslide. 
6.	Create link to input file format page. Then users could know how to load slide and use which lens
7.	In registration, we should describe unique feature better and link to Semi_Automated Registration page (The example at here could be “sample WSI”)
8.	Mention click the same unique location is just for searching area. 
9.	Use “Load last calibration” to skip Low Resolution
10.	In High Resolution, we need mention digital image in interface is zoomed area of Low Resolution 
11.	In high Resolution, we should mention WSI image might not focused well.
Input file
1.	ROIs should have some characteristics
2.	Description of task should be more detail (not just Q_OP1).

**Comment by ajhandoko** [comment]
I have a few questions the numbers correspond with your notes.

2. We still need to find a sample WSI image. I'm not sure where to find it
3. "How to start eeDAP" Like opening the application?
4. Where do I need the mention "Extract ROI" button? It is already explained on the "Input Screen Window" page
6. Where do you want me to create a link to the page from?
7. Where should I create the link for the "Semi_Automated Registration" page?

**Comment by qigongFDA** [comment]
We should add a section about available WSI formats. 
For now, we could load .svs, .ndpi and .tif formats. And Bioformat will release a new version, which could load .czi image. We should mention all of them in our manual.

**Comment by qigongFDA** [comment]
Wei-Chung helps us find a CMU link, which provides WSI sample images.
http://openslide.cs.cmu.edu/download/openslide-testdata/

**Comment by brandon-gallas** [comment]
There are formats we have explicitly tested and those that are theoretically possible thanks to the bioformats software.
Is there a "Formats Supported" documentation for bioformats software?
If so, you should point to that.

**Comment by qigongFDA** [comment]
I found this link from Bio-Format website last week. I also sent email to double check which column we should focus on, and what rating is a good rating. I am still waiting for reply.  
http://www.openmicroscopy.org/site/support/bio-formats5.1/supported-formats.html

**Comment by brandon-gallas** [comment]
More sample WSI images

I found some WSI images on the web. We can provide links to these instead of posting some ourselves. Here is the click through to the images
http://openslide.org/
In the section “About OpenSlide”, click on “Aperio (.svs, .tif)” takes you here http://openslide.org/formats/aperio/
At the bottom of the page is a section, “Test Data” that takes you here http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/

Here is the click through to images on openmicroscopy.
http://www.openmicroscopy.org/site/products/bio-formats
In the middle of the page is a link to “file formats” that takes you here http://www.openmicroscopy.org/site/support/bio-formats5.1/supported-formats.html
Near the top of the list is Aperio SVS TIFF that takes you here http://www.openmicroscopy.org/site/support/bio-formats5.1/formats/aperio-svs-tiff.html
In the middle of the page is a bullet “public sample images” that takes you here http://downloads.openmicroscopy.org/images/SVS/

**Comment by qigongFDA** [comment]
I download one WSI image http://downloads.openmicroscopy.org/images/SVS/77917.svs and create a sample input file. It works well. 

We should change all sample files base on the images on these two websites. We should also use those images in manual Semi-Automated Registration page.

**Comment by brandon-gallas** [comment]
Do not change all sample files. Do not use new images for semi-automated registration page. We do not have the corresponding glass slides.

Instead change create new directory devInputfiles, copy the files from the sample_inputfiles directory into the new devInputfiles directory, and then delete the files in the sample_inputfiles directory (create, copy and delete necessary because git doesn't allow renaming files or directories).

Then...
You should download a sample WSI image of each format you find, create a corresponding input file in the sample_inputfiles directory (include the url location for the WSI image in the header part of the inputfile), and test whether or not eeDAP works.

Brandon
