### ISSUE TITLE
Summarize updates

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#13]
Please include an "Update Summary" file like you did for iMRMC discussing the major updates.

**Comment by brandon-gallas** [comment]
I'm not sure if these updates are to get to 3p0 or 3p1:
i.	Auto-registration of every ROI (speeds up the study)
ii.	Add option to not save MicroRT ROIs and WSI-extracted ROIs
iii.	Add a back button
iv.	Allow rotated slides, or equivalently, allow stages with different orientations
v.	Use “BioFormats” procedures to eliminate proprietary routine for reading proprietary WSI images to simplify installation and allow functionality in Linux and 62-bit windows
vi.	Migrate documentation to DrExplain which outputs html and pdf versions

**Comment by qigongFDA** [comment]
I have created the UPDATES_eeDAP.md file. I think the updates in your comment is for 3p0. I think the release version in GITHUB is 3p1. I add the 3p1's updates in UPDATES_eeDAP.md too. 

Our current code has several new updates. For example, 1. Create last offset button, 2. New Retical
3. Remember last browsed input file directory. We could think about release 3p2 for them.

**Comment by qigongFDA** [comment]
Could we close this issue?

**Comment by brandon-gallas** [comment]
I do not see a link to the updates file on the releases page like I see for iMRMC. Please create the link.
