### ISSUE TITLE
Prepare for a new version release v4p0

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#20]
Thanks with your email. Yes, let's create a new version v4p0, including the compiled version for windows.

I'm rewriting your summary here for you to describe the updates. Please add the model numbers:
 1. New hardware supported:
- Prior Stage (model number)
- USB 3.0 camera
- Klarman Rulings reticle (model number)
 2. User manual overhaul.
 3. New workflow updates:
- "Use offset button" is added during registration to avoid camera and eyepiece registration.
- "Hide reticle" and "Show reticle" buttons are added to the task collection gui.
 4. Improve "Best Registration" button performance.
 5. Improve Camera_stage_review utility application interface and "take image" button.

**Comment by qigongFDA** [comment]
I use Matlab 2016a compile the functions. The camera image freeze when the main study begin. But camera could take task image and save it   All other features work well.

**Comment by qigongFDA** [comment]
The problem might come from different versions of Matlab. 
I tried to use R2016 to compile eeDAP3.0. The camera has same problem. 
I also tried to use R2013 to compile eeDAP3.0 and eeDAP4.0. Both of them work. 
But R2013 doesn't have USB camera toolbox. We have to use R2016.

**Comment by qigongFDA** [comment]
The save GUI.m warning isn't reason.
I found the camera preview function works well in Administrator_Input_Screen.m and Stage_Allighment.m. It has problem only in GUI.m. 
One big difference between them is GUI.m run after Administrator_Input_Screen.m is closed. Thus, I add add uiwait(handles_GUI) command in Administrator_Input_Screen.m. It could keep  Administrator_Input_Screen running until GUI.m finishes. Then the camera problem disappear.

**Comment by qigongFDA** [comment]
I release the new Windows version. Could you close this issue?

**Comment by brandon-gallas** [comment]
The iMRMC window says version 3p0 Beta.
Please change to 3p0.
