### ISSUE TITLE
video manual

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/eeDAP#25]
Videos are created and saved in /raidb/qigong/eeDAPvideoManual. 
The digital mode script is saved in the same directory.

**Comment by brandon-gallas** [comment]
Please upload videos to YouTube.

**Comment by qigongFDA** [comment]
Both videos have been uploaded.
Digital: https://www.youtube.com/watch?v=8fOYwzjwIAc
MicroRT: https://www.youtube.com/watch?v=L81Brta9_3E
