### ISSUE TITLE
Update the current user manual with the draft version

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#28]

**Comment by brandon-gallas** [comment]
Please update the user manual quickly (move draft to final).
I think we should split the Run Software into two pages:
 * Quick run in digital mode
 * Run on the microscope

**Comment by qigongFDA** [comment]
I just see this comment. Current full version hasn't been splitted. I will split it in draft version first.

**Comment by brandon-gallas** [comment]
Update the manual to show the options for the "saveimages" flag in the input file. Also check to see if there are other flags that have more information.

**Comment by brandon-gallas** [comment]
I was reading the documentation for getting started. I see that the link you provide for downloading an image has many images available. This is what needs to be more specific. Tell the user to download the images that correspond to the sample input files you created.

Top priority.

**Comment by brandon-gallas** [comment]
The link to the microscope user manual does not work. FIX. I think we should collect and archive our own versions of the manuals instead of relying on links.
Please include a section somewhere about Kohler illumination. This calibration process should be discussed in the user manual somewhere. Here is a link with a tutorial on Kohler illumination. You can include this in the discussion. https://www.microscopyu.com/tutorials/kohler

**Comment by qigongFDA** [comment]
Upload device manuals to eeDAP repository, and add Kohler illumination calibration tutorial to eeDAP user manual. Can we close this issue.

**Comment by brandon-gallas** [comment]
No. What you have added is not enough. The link is informative, but do you think you could use that link to calibrate the microscope. I could not.

I would like a separate section or subsection or some kind of "Microscope set up" section.

Also, I noticed the links you used to pdfs. They are not useful. Please update.

**Instead of** 

https://github.com/DIDSR/eeDAP/blob/master/000_docs/hardware_manual/Microscope/olympus_specification_and_manual.pdf

**Use this**

https://github.com/DIDSR/eeDAP/raw/master/000_docs/hardware_manual/Microscope/olympus_specification_and_manual.pdf

Thanks Qi.
