### ISSUE TITLE
Stage and camera control utility functions.

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#3]
We need to create documentation and possibly stand-alone executables that can do some of the following:
 * Take a picture and save it to a file.
 * Get stage coordinates.
 * Move to stage coordinates.

**Comment by qigongFDA** [comment]
Build a stand-alone executable named "camera_stage_review", which could do the above processing. It works on old and new system. I commit it to eeDAP/compiled folder.

**Comment by qigongFDA** [comment]
We should add a feature: when user click "take image" button, open a window to allow user save image. The first time default directory should be the GUI file directory. The following times should be last directory.

**Comment by qigongFDA** [comment]
The update has merged to master. I think we could close this issue.

**Comment by brandon-gallas** [comment]
Is there documentation on this "Utility Function"?
If so, please tell me how to find it.
If not, please create a topic: "Stage and Camera Control Utility Functions" after the workflow topics.

**Comment by qigongFDA** [comment]
I am sorry. I haven't update the documentation about it. I will do it today.

**Comment by qigongFDA** [comment]
I added the  "Stage and Camera Control Utility Functions" into the manual. Please have a look. Thank you.

**Comment by qigongFDA** [comment]
I added the "Stage and Camera Control Utility Functions" into the manual. The whole manual still need editing. I think we could create a long term issue for manual and close this issue. Thank you.

**Comment by brandon-gallas** [comment]
Please create an issue for a whole-manual overhaul.
