### ISSUE TITLE
"Refine Registration" should move the stage to the first stage position

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#32]
I clicked on Refine Registration. High-resolution registration began. The WSI patch was shown, but the stage did not move to the corresponding location. Of course, I could click "Load last calibration", but it should be done automatically.

**Comment by qigongFDA** [comment]
Call "Load_last_calibration" function at end of "Refine Registration" function.

**Comment by brandon-gallas** [comment]
Do we have a button to "Use Current Registration" ?

**Comment by qigongFDA** [comment]
Let's change the "refine registration" button to "Restart Registration" so that the user can recover without redoing the registration of other slides.

**Comment by qigongFDA** [comment]
Change "Load last registration" to "Load registration and refine"

**Comment by qigongFDA** [comment]
Add "restart registration" button to restart low resolution registration. Can we close this issue?

**Comment by brandon-gallas** [comment]
yes
