### ISSUE TITLE
We need a better exit when image file name is incorrect

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#37]
If the file name is incorrect, the program closes with errors. It should close more purposefully.

**Comment by brandon-gallas** [comment]
Tell the user that the file doesn't exist and close the program or ask to load a new input file.
Also expand the file contents shown to the user.

**Comment by qigongFDA** [comment]
Any error in the input file will alert the user and return to the administrator GUI. I think this is done. 

Brandon agrees. And says I did better than asked.
