### ISSUE TITLE
Provide image name and thumbnail of slide being registered 

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#39]

**Comment by qigongFDA** [comment]
The image name and thumbnail have been added to global registration interface. Can we close this issue?

**Comment by qigongFDA** [comment]
Brandon says the issue is completed.

**Comment by brandon-gallas** [comment]
Can we add the slide label too, if it exists?

**Comment by qigongFDA** [comment]
For now, The image name is the main information in label. We don't have to add label. I talked with Brandon. We decide to close this issue for now.
