### ISSUE TITLE
Move items from FDA SVN 

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/eeDAP#4]
We should move items from FDA SVN to GITHUB

**Comment by qigongFDA** [comment]
Hello Brandon,

I cleaned and updated the eedap code. 
FDA SVN,
I updated the trunk to the latest version. 
GITHUB,
I copied the FDA SVN truck to GITHUB qigong branch. 

There is one more question for the code. For FDA SVN, we have a branch about zoom and pan. I made zooming and panning working, but not works well. And we decided to leave that branch alone.  If we want to move most or ever everything from FDA SVN to GITHUB, do you think we should build a branch in GITHUB for zoom and pan code? Thank you.

Sincerely,
Qi

**Comment by brandon-gallas** [comment]
Yes. Please create a separate branch and call it panANDzoom

Brandon

**Comment by brandon-gallas** [comment]
When we meet tomorrow, please let me know if the eeDAP/qigong branch is ready to be merged to the master branch.

**Comment by qigongFDA** [comment]
Brandon says to keep things as is for now and close this issue.
