### ISSUE TITLE
Create input file for MSKCC WSI images

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#42]
See if you can show the same FOVs.
It should be a simple scale factor between the location and size for their image (.23mpp) vs our image (.25mpp).

**Comment by qigongFDA** [comment]
It is not that easy to choose same FOV. Because, they padded the empty place. So the difference includes scaling and moving. But I think I can do it. Please give me the path where you save the image.

**Comment by brandon-gallas** [comment]
Yes, it will be a bit tough to find the locations. Good luck with that.

I will upload the images on Monday. It will be faster than if I do it remotely.

Brandon

**Comment by brandon-gallas** [comment]
I have uploaded the files to
/raida/bdg/000_visitors/conway_raida/wsi_archive/20170710mcsMSKCC/

I have updated the svnFDA/eeDAP/000_image_upload_log/image_upload_log.xlsx
except I don't have full information for the scanner models. Please ask about that and upload the log with that information.

Let me know if you have any questions.

B

**Comment by qigongFDA** [comment]
I create input files MC_HE1_ndpi, MC_HE2_ndpi, MC_HE1_svs, MC_HE2_svs for MSKCC images. And committed to master branch. Can you close this issue?

**Comment by brandon-gallas** [comment]
Perfect
