### ISSUE TITLE
Catalog different reticles

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#5]
@qigongFDA @aanam 

I will show Qi the reticles we have. We should catalog them and draw them in FDASVN eeDAP\000_docs\eeDAP_screen_shots_and_drawings\reticle.pptx

Qi, you need this for the eeDAP-version of the mitotic counting study.

Jessica could possibly do the drawing after watching Qi do one.

Brandon

**Comment by qigongFDA** [comment]
I drew the reticle KR-871 in both reticle.pptx and Matlab. I think that might be best reticle we have for the project. We might need to discuss whether we need to draw the rests now.

**Comment by brandon-gallas** [comment]
Good job.
Please indicate where the pptx file is located. We do not need to catalog the rest right now unless we want to give Jessica that job.

Brandon

**Comment by qigongFDA** [comment]
The .pptx file is still located at FDASVN eeDAP\000_docs\eeDAP_screen_shots_and_drawings\reticle.pptx

**Comment by qigongFDA** [comment]
I drew all reticles in reticle.pptx.
