### ISSUE TITLE
running with ImageScope, xml reformat

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#59]
We talked about errors that appeared when running eeDAP with a new version of ImageScope.
I believe the errors are from ImageScope has a new format for the xml file.
It is not a big difference because everything will still run after clicking ok to the errors.
Please get to the bottom of this and let me know.

Brandon

**Comment by qigongFDA** [comment]
I have updated the xml generate function for new version imagescope.
