### ISSUE TITLE
Investigate poor registration on PHH3 slides

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#6]
We may need to try different channels or contrast enhancement.

This issue is in response to email from Qi. Qi wrote that: "The registration of PHH3 during task part has a little problem. there are about 3 out of 40 images can't register even with best_register button. We never face this problem for HE image."

**Comment by qigongFDA** [comment]
We find out the reason for this problem. When we do the correlation registration, the software automatically pads boundary for large image to do correlation. The size of output file equals to the summation of sizes of two images. 

Now we only use the center area of the output file with size equals to the subtraction of two images. I test 10 images and all of them work well.   

I think we could close this issue

**Comment by qigongFDA** [comment]
I think we could close this issue
