### ISSUE TITLE
New task to get WSI ROI position base on glass slide

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/eeDAP#63]
A new task to get WSI ROI position base on glass slide. It is only available in micro_rt mode

**Comment by qigongFDA** [comment]
create new task "task_get_WSI_position.m" to get WSI ROI position based on glass slide.

**Comment by brandon-gallas** [comment]
Done. Works great. Please make sure this task makes it into the documentation. Once I see it there I will close this issue.

**Comment by qigongFDA** [comment]
Edit code to save WSI and camera images

**Comment by qigongFDA** [comment]
Added this task to eeDAP manual.
