### ISSUE TITLE
eeDAP in the cloud: NCIPhub

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#64]
Please create a tool on NCIPhub that runs eeDAP.

**Comment by brandon-gallas** [comment]
From Qi: We got reply from NCIP hub 

“Qi,

That's great your Matlab code is working.  We do have a solution for running Windows-based applications on the hub and would be happy to work with you.  The Windows solution requires a deeper discussion as it requires the purchasing of licenses and time to setup on NCIPhub.  If you would like to meet to discuss the scope your project and the need for MS Windows resources we can setup a meeting and would like to include the PI of NCIPhub as well.  Please let us know how you would like to continue.”

It is possible. We might need to purchase license. But I haven’t got any reply from imagescope. Thus, I can’t do the test running on our local computer.

What do you think we should do first? 1. Do the imagescope discussion with the NCIP hub. 2. Ask the hub to help us install eeDAP (without imagescope)? Thank you.

Regards,
Qi

**Comment by brandon-gallas** [comment]
Focus on getting eeDAP to work without imagescope. In parallel, start a conversation on 1. I am happy to participate in a meeting with them.

**Comment by qigongFDA** [comment]
Reply from Leica Biosystems
Hello Qi Gong,

Thank you for contacting Leica support.
Our ImageScope application is written only for the Microsoft Windows 7 and 8.1 Professional operating system.
There are no plans to port it to Linux at this time.

I have heard of viewer applications such as Fiji, or ImageJ that may be an alternative, but they are not supported by Leica.
Thank you.

Regards,

David Bajt  |  Cerebro Technical Support Specialist  |  Leica Biosystems
