### ISSUE TITLE
Investigate slow stage

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#7]
This is in response to Qi's email: "The response of new stage MAC 6000 is a little slow. We send moving comment, it has a few second delay before moving.

I think the delay comes both from MCR and MAC6000 device. I didn't try to fit it today. Because it is working now, and the delay is not very long. I am afraid of brake it during the fixing. You can have a look of it next Monday. If you want to improve it, I will try to fix before next friday."

**Comment by qigongFDA** [comment]
I found out the slow might come from the computer. We plan to figure out whether it is hard drive problem.

**Comment by qigongFDA** [comment]
I test the stage controller again. It needs about 1-2s to response. I think it is acceptable. Close this issue for now.
