### ISSUE TITLE
Registration between two WSI

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/eeDAP#83]
We will create a new feature to register two WSI images. Then we can share annotation from one image to the other.

**Comment by qigongFDA** [comment]
Here is a potential GUI interface.
![image](https://user-images.githubusercontent.com/12702285/45642170-8172c800-ba85-11e8-9d1a-66117995750d.png)
[WSIregistration.pptx](https://github.com/DIDSR/eeDAP/files/2389758/WSIregistration.pptx)

**Comment by brandon-gallas** [comment]
Good idea.

**Comment by qigongFDA** [comment]
Here is the screen cut of GUI.
![Capture](https://user-images.githubusercontent.com/12702285/54213382-adae5500-44ba-11e9-8105-d0418b173e40.PNG)

**Comment by qigongFDA** [comment]
I create GUI to do the registration between WSIs.
WSI A: Basic WSI. We have positions for this WSI.
WSI B: Target WSI. We want position for this WSI.

Procedure:
1. Load two WSIs
2. Click "Start Registration" button
3. Use the 3 buttons and click WSI thumbnail to do registration.
4. After the registration done, the "Transformation Equation" displayed. 
5. Click "Load WSI A position" button to load WSI A's positions.
6. Click "Export position for the target WSI" button to generate the positions for target WSI and save to disc.

Format of position file: 
1. CSV.
2. Two columns, (X and Y)

**Comment by brandon-gallas** [comment]
Nice. Can you add a feature that allows the user to manually input an x,y position on slide A and return the x,y position on slide B?

Also, work on the documentation and we will find someone to review for feedback. Do the documentation in some simple format that we can ultimately add as a wiki FAQ page.

The priority for documenting is not high. Glad that we now have the tool.

**Comment by KKIverson** [comment]
Have you finished this new feature: Registration between two WSI?

**Comment by brandon-gallas** [comment]
Yes. The code is here 
https://github.com/DIDSR/eeDAP/tree/master/utilities/WSI_to_WSI_registration

The specific script to run is https://github.com/DIDSR/eeDAP/blob/master/utilities/WSI_to_WSI_registration/WSIregistration.m

Instructions are in the comment above [LINK](https://github.com/DIDSR/eeDAP/issues/83#issuecomment-472054927) and this picture might help too.

![image](https://user-images.githubusercontent.com/12649789/86155186-0ea7d500-bad2-11ea-9eef-227b19ede635.png)

**Comment by jiajundeng** [comment]
> I create GUI to do the registration between WSIs.
> WSI A: Basic WSI. We have positions for this WSI.
> WSI B: Target WSI. We want position for this WSI.
> 
> Procedure:
> 
> 1. Load two WSIs
> 2. Click "Start Registration" button
> 3. Use the 3 buttons and click WSI thumbnail to do registration.
> 4. After the registration done, the "Transformation Equation" displayed.
> 5. Click "Load WSI A position" button to load WSI A's positions.
> 6. Click "Export position for the target WSI" button to generate the positions for target WSI and save to disc.
> 
> Format of position file:
> 
> 1. CSV.
> 2. Two columns, (X and Y)

Hi, I would like to ask is it possible that you can offer me the mathematical prove or theoretical support while you do the whole slide image registration? In other words, what is your underlying principle when performing the wsi registration process. What is your reference paper when implementing the wsi registration?

**Comment by brandon-gallas** [comment]
The registration is described in these papers.
* Gallas, Brandon D., Marios A. Gavrielides, Catherine Conway, Adam Ivansky, Tyler Keay, Wei-Chung Cheng, Jason Hipp, and Stephen M. Hewitt. “Evaluation Environment for Digital and Analog Pathology (EeDAP): A Platform for Validation Studies.” J Med Img 1 (2014): 037501. https://doi.org/10.1117/1.JMI.1.3.037501. **[Gallas2014_J-Med-Img_v1p037501.pdf](https://github.com/DIDSR/eeDAP/files/5979381/Gallas2014_J-Med-Img_v1p037501.pdf)**


* Q. Gong, B. P. Berman, M. A. Gavrielides, and B. D. Gallas, “Registration accuracy between whole slide images and glass slides in eeDAP workflow,” in Medical imaging 2018: digital pathology, 2018, vol. 10581. https://doi.org/10.1117/12.2293189 **[Gong2018_Proc-SPIE_v10581p1058118.pdf](https://github.com/DIDSR/eeDAP/files/5979385/Gong2018_Proc-SPIE_v10581p1058118.pdf)**
